export const STATIONS = [
  { id: '1',
    name: "Ciencias UV",
    loc: 'Valparaíso, Chile',
    color: '#33ff00',
    lat: -33.02705, 
    lng: -71.63875, 
    elev: '77.58 masl',
    instdate:'2024',
    timezone: 'America/Santiago',
    brand: 'Hobo RX3000',
    status: 'ACTIVE', 
    images: [
      "REMCI-UV/images/estacionUV.png",
      "REMCI-UV/images/cameraciencias.gif",
      "REMCI-UV/images/2025-07-28-07-49-19.jpg"
    ],
    variables: [
      "Temperature",
      "Relative Humidity",
      "Dew Point",
      "Wind Speed",
      "Wind Direction",
      "Wind Gusts",
      "Atmospheric Pressure",
      "Solar Radiation",
      "Accumulated Rain"
    ],
    temp: 16.2, 
    humidity: 62, 
    windSpeed: 0.5, 
    windDir: 216, 
    solarRad: 1 },

  { id: '2', 
    name: "Pocuro UV",
    loc: 'Los Andes, Chile', 
    color: '#8b0cc6',
    lat: -32.86967, 
    lng: -70.61523, 
    elev: '800 masl',
    instdate:'March 23, 2026',
    timezone: 'America/Santiago',
    brand: 'Hobo RX3000', 
    status: 'ACTIVE',
    images: [
      "REMCI-UV/images/pocuro1.jpg",
      "REMCI-UV/images/pocuro2.gif",
      "REMCI-UV/images/pocuro3.jpg",
    ],
    variables: [
      "Temperature",
      "Relative Humidity",
      "Dew Point",
      "Wind Speed",
      "Wind Direction",
      "Wind Gusts",
      "Atmospheric Pressure",
      "Solar Radiation",
      "Accumulated Rain"
    ],
    temp: 18.5, 
    humidity: 45, 
    windSpeed: 0.5, 
    windDir: 216, 
    solarRad: 1}, 

  { id: '3', 
    name: "La Reserva",
    loc: 'Villa Alemana, Chile', 
    color: '#fff700',
    lat: -33.04374, 
    lng: -71.33947, 
    elev: '228.87 masl',
    instdate:'March 30, 2026',
    timezone: 'America/Santiago',
    brand: 'Davis Vantage Pro2',
    status: 'IDLE',
    images: [
      "REMCI-UV/images/reserva1.jpg",
      "REMCI-UV/images/presentation.jpeg",
      "REMCI-UV/images/instalacion.jpeg",
      "REMCI-UV/images/davis2.1.png"
    ],
    variables: [
      "Temperature",
      "Relative Humidity",
      "Dew Point",
      "Wind Speed",
      "Wind Direction",
      "Wind Gusts",
      "Atmospheric Pressure",
      "Solar Radiation",
      "Accumulated Rain"
    ],
    temp: 17.8, 
    humidity: 55, 
    windSpeed: 0.5, 
    windDir: 216, 
    solarRad: 1 },
  
  { id: '4', 
    name: "Home",
    loc: 'Villa Alemana, Chile', 
    color: '#1602eb',
    lat: -33.061188,
    lng: -71.396009, 
    elev: '160.72 masl',
    instdate: 'July 28, 2026',
    timezone: 'America/Santiago',
    brand: 'DIY Weather Station',
    status: 'MAINTENANCE',
    images: [
      "REMCI-UV/images/cameraciencias.gif",
    ],
    variables: [
      "Temperature",
      "Relative Humidity",
      "Dew Point",
      "Wind Speed",
      "Wind Direction",
      "Wind Gusts",
      "Atmospheric Pressure",
      "Solar Radiation",
      "Accumulated Rain"
    ],
    temp: 17.8, 
    humidity: 55, 
    windSpeed: 0.5, 
    windDir: 216, 
    solarRad: 1 }

];

// BUG: locally the images paths need the REMCI-UV at the begining, but in GitHub we don't need it
// Try to fix this in vite.config.js, here the base root is set to "/REMCI-UV"
// NOTE: for consistency, keep the ids as strings